### ISSUE TITLE
初始化报错

### ISSUE THREAD

**Issue by smadey** [Cyberbolt/baota#4]
```
正在设置面板端口
Traceback (most recent call last):
  File "script.py", line 95, in <module>
    main()
  File "script.py", line 79, in main
    bt_init(data['port'], data['username'], data['password'])
  File "script.py", line 31, in bt_init
    child.expect('.*：'.encode('utf-8'))
  File "/usr/local/lib/python3.7/dist-packages/pexpect/spawnbase.py", line 344, in expect
    timeout, searchwindowsize, async_)
  File "/usr/local/lib/python3.7/dist-packages/pexpect/spawnbase.py", line 372, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python3.7/dist-packages/pexpect/expect.py", line 179, in expect_loop
    return self.eof(e)
  File "/usr/local/lib/python3.7/dist-packages/pexpect/expect.py", line 122, in eof
    raise exc
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0x7fa568ec88>
command: /usr/bin/bt
args: ['/usr/bin/bt']
buffer (last 100 chars): b''
before (last 100 chars): b't.pl: No such file or directory\r\n/usr/bin/bt: line 339: /usr/bin/python: No such file or directory\r\n'
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: None
flag_eof: True
pid: 8
child_fd: 5
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile(b'.*\xef\xbc\x9a')
```

**Comment by Cyberbolt** [comment]
请你发一下引起报错的命令

**Comment by Cyberbolt** [comment]
如果有前文更好

**Comment by smadey** [comment]
是在 arm 的 QNAP 上，型号 TS-212P3
全都是默认配置

**Comment by Cyberbolt** [comment]
请你把所有步骤输入的命令复制过来看看，有截图更好

**Comment by Cyberbolt** [comment]
请你把所有步骤输入的命令复制过来看看，有图片更好

**Comment by smadey** [comment]
是可视化界面

**Comment by smadey** [comment]
命令应该是 `docker run -itd --net=host --restart=always --name baota-1 cyberbolt/baota -port 8888 -username cyberbolt -password abc123456`
![image](https://user-images.githubusercontent.com/4351454/135749487-2f7b46d8-0ced-4f24-902f-cc552a57f7b7.png)
![image](https://user-images.githubusercontent.com/4351454/135749500-41471fd1-0b3a-4325-bbb8-8810108aed54.png)

**Comment by smadey** [comment]
成功了。。。应该是之前没用 host 模式的问题，刚为了复现，所以特意用了 host 模式

**Comment by smadey** [comment]
![image](https://user-images.githubusercontent.com/4351454/135749662-58c01f4e-47ea-4303-9e68-1903468f15de.png)
这个配置会失败

**Comment by Cyberbolt** [comment]
图形化看不太出来，建议直接在终端使用命令创建。配置好 --net=host 和 挂载目录 便不会出错了

**Comment by smadey** [comment]
> 接在终端使用命令创建。配置好 --net=host 和 挂载目录 便不会

嗯，直接在终端执行命令就没有问题，已经好了，谢谢
